services:
    media-api:
        container_name: media-api
        image: media-api
        mem_reservation: 256M
        mem_limit: 512M
        cpus: 1.0
        build:
            context: ../../backend/media
            dockerfile: Dockerfile
            args:
                - MAINTAINER=${EMAIL}
        environment:
            - CLOUDINARY_CREDENTIALS_PATH=/run/secrets/cloudinary_credentials
            - ALLOWED_ORIGINS=api.${HOSTNAME}
            - SERVER_DOMAIN=[::]:8000
        networks:
            - backend-network
            - traefik-network
        secrets:
            - cloudinary_credentials
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

secrets:
    cloudinary_credentials:
        file: ./secrets/cloudinary/credentials.json
