services:
    music-api:
        container_name: music-api
        image: music-api
        mem_reservation: 256M
        mem_limit: 512M
        cpus: 1.0
        build:
            context: ../../backend/music
            dockerfile: Dockerfile
            args:
                - MAINTAINER=${EMAIL}
        environment:
            - REDIS_CREDENTIALS_PATH=/run/secrets/redis_credentials
            - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
            - ALLOWED_ORIGINS=api.${HOSTNAME}
            - COMPANY_NAME=${COMPANY_NAME}
            - COOKIE_DOMAIN=${HOSTNAME}
            - SERVER_DOMAIN=[::]:8000
        networks:
            - backend-network
            - traefik-network
        secrets:
            - redis_credentials
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

secrets:
    redis_credentials:
        file: ./secrets/redis/credentials.json
